<?php

namespace AppBundle\Repository;

/**
 * AppParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppParamRepository extends \Doctrine\ORM\EntityRepository
{
}
