<?php

namespace NumoBundle\Repository;

/**
 * compagnyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class compagnyRepository extends \Doctrine\ORM\EntityRepository
{
}
