<?php

namespace NumoBundle\Repository;

/**
 * EvtDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvtDateRepository extends \Doctrine\ORM\EntityRepository
{
}
