<?php

namespace NumoBundle\Repository;

/**
 * ModerationRefusalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModerationRefusalRepository extends \Doctrine\ORM\EntityRepository
{
}
