<?php

namespace NumoBundle\Repository;

/**
 * pageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pageContentRepository extends \Doctrine\ORM\EntityRepository
{
}
