<?php

namespace NumoBundle\Repository;

/**
 * PricingInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
