<?php

namespace NumoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PublishedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishedRepository extends EntityRepository
{
}
