<?php

namespace NumoBundle\Repository;

/**
 * PublishedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishedRepository extends \Doctrine\ORM\EntityRepository
{
}
