<?php

namespace NumoBundle\Repository;

/**
 * SnLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
