<?php

namespace NumoBundle\Repository;

/**
 * SocialNetworkLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialNetworkLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
